FORMAT: 1A
HOST: https://ride-my-way-2.herokuapp.com/api/v2/

# Ride-My-Way

## Project Overview
Ride-My-Way App is a carpooling application that provides drivers with the ability to create ride offers and passengers to join available ride offers
## Required Features
1. Users can create an account and log in.
2. Drivers can add ride offers..
3. Passengers can view all available ride offers.
4. Passengers can see the details of a ride offer and request to join the ride. E.g What time the ride leaves, where it is headed e.t.c
5. Drivers can view the requests to the ride offer they created.
6. Drivers can either accept or reject a ride request.

The following header will be required when making the API calls
```
Content-Type : application/json
```
After  authentication, the secured endpoints will require you to include the bearer token that is sent with the login reponse.
```
Authentication: Bearer [Token]
```

## User Registration [/auth/signup]

### Sign up [POST]

Creates a new user accounts.

+ Request (application/json)

        {
            "username":"Derrick",
            "email":"derrick@gmail.com",
            "contact":"0729765267",
            "car_model":"Mercedez E350",
            "car_regno":"KCF809U",
            "password":"Derrick@54y",
            "confirm_password":"Derrick@54y"
        }
        
+ Response 201 (application/json)

        {
            "message": "Registration Successfull"
        }

## Login [/auth/login]

### Sign in[POST]

The user can login with their username and password. The response includes a token which will be used in future requests. The token 
automatically expires after some time when the user is not accessing the API.

+ Request (application/json)

        {
            "username": "Derrick"
            "password": "Derrick@54y"
        }
        
+ Response 200 (application/json)

        {
            "message": "Login successfull!",
            "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MzA3NTQ5MDAsIm5iZiI6MTUzMDc1NDkwMCwianRpIjoiZDgwZDVhZjctNTBiNC00YTA5LThlMzctOGQ1NGM2M2NiNDJkIiwiZXhwIjoxNTMwNzU1ODAwLCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIn0.XzZZHEQ21aBk_HJa0T3W4a5KcwpVdGQy5_JXLQnSLNU"
        }

## Creating a Ride Offer [/rides]

### Create a ride offer [POST]

An authenticated user can create a ride request. 

+ Request (application/json)

        {
            "destination": "Upper Hill",
            "from_location": "Kabete",
            "departure_time" : "13:30",
            "price":"null"
        }

+ Response 201 (application/json)

        {
         "Created_ride_offer": {
                "created_by": "Derrick",
                "date_created": "Thu, 05 Jul 2018 04:50:23 GMT",
                "departure_time": "13:30",
                "destination": "Upper Hill",
                "from_location": "Kabete",
                "price": "null"
            }
        }
        
### Get all ride offers[GET]
+ Response 200 (application/json)

        {
            "all ride offers": [
                {
                    "created_by": "Derrick",
                    "date_created": "Thu, 05 Jul 2018 01:50:25 GMT",
                    "departure_time": "13:30",
                    "destination": "Upper Hill",
                    "from_location": "Kabete",
                    "id": 1,
                    "price": "null"
              }
            ]
        }

## User can GET ride by ID [/rides/1]

### Get all Requests[GET]

A user can get a ride by its id.

+ Response 200 (application/json)

        {
            "Ride Offer:": {
                "created_by": "Derrick",
                "date_created": "Thu, 05 Jul 2018 01:50:25 GMT",
                "departure_time": "13:30",
                "destination": "Upper Hill",
                "from_location": "Kabete",
                "id": 1,
                "price": "null"
            }
        }

## User can respond to a ride request [/requests/{request_id}]